# Generated by Django 2.0.2 on 2018-02-12 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studioname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('sales', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('url', models.CharField(default='http://webcourse.cs.hut.fi/example_game.html', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Game_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_score', models.TextField(default='NOSAVE')),
                ('save_items', models.TextField(default='NOSAVE')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameshop.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game_state',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameshop.Profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='bought',
            field=models.ManyToManyField(blank=True, through='gameshop.Game_state', to='gameshop.Profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameshop.Developer'),
        ),
        migrations.AddField(
            model_name='developer',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gameshop.Profile'),
        ),
    ]
