# Generated by Django 2.0.2 on 2018-02-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0002_auto_20180212_1646'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game_state',
            unique_together={('game', 'profile')},
        ),
    ]
