# Generated by Django 2.0.1 on 2018-02-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0002_auto_20180216_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(default='Undefined', max_length=20),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
