# Generated by Django 2.0.2 on 2018-02-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0003_auto_20180212_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_state',
            name='submitted_score',
            field=models.IntegerField(null=True),
        ),
    ]
