# Generated by Django 2.0.2 on 2018-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0004_game_state_submitted_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_state',
            name='submitted_score',
            field=models.FloatField(null=True),
        ),
    ]
