# Generated by Django 2.0.1 on 2018-01-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0005_auto_20180117_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.IntegerField(default=0)),
                ('owned', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameshop.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameshop.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='games_bought',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_dev',
        ),
        migrations.AddField(
            model_name='sale',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameshop.Profile'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameshop.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(through='gameshop.Ownership', to='gameshop.Game'),
        ),
    ]
