# Generated by Django 2.0.2 on 2018-02-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0005_auto_20180214_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_state',
            name='save_score',
            field=models.FloatField(default=0),
        ),
    ]
