# Generated by Django 2.0.1 on 2018-01-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0006_auto_20180123_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownership',
            name='owned',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='sales',
        ),
        migrations.AddField(
            model_name='game',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
