# Generated by Django 2.0.2 on 2018-02-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0006_auto_20180214_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_state',
            name='save_items',
            field=models.TextField(null=True),
        ),
    ]
