# Generated by Django 2.0.1 on 2018-02-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0007_profile_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
