# Generated by Django 2.0.1 on 2018-01-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0007_auto_20180123_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='game',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='owner',
        ),
        migrations.AddField(
            model_name='ownership',
            name='owned',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
