# Generated by Django 2.0.1 on 2018-01-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0008_auto_20180123_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='game',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='bought',
            field=models.ManyToManyField(to='gameshop.Profile'),
        ),
        migrations.DeleteModel(
            name='Ownership',
        ),
        migrations.AddField(
            model_name='developer',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gameshop.Profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='gameshop.Developer'),
            preserve_default=False,
        ),
    ]
