# Generated by Django 2.0.1 on 2018-02-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0008_profile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
