# Generated by Django 2.0.1 on 2018-02-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0010_auto_20180223_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
