# Generated by Django 2.0.1 on 2018-01-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0010_auto_20180123_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_state', models.TextField(default='NOSAVE')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameshop.Game')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameshop.Profile')),
            ],
        ),
    ]
