# Generated by Django 2.0.1 on 2018-01-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0011_game_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_state',
            name='game',
        ),
        migrations.RemoveField(
            model_name='game_state',
            name='profile',
        ),
        migrations.DeleteModel(
            name='game_state',
        ),
    ]
