# Generated by Django 2.0.1 on 2018-02-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0011_auto_20180223_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
    ]
