# Generated by Django 2.0.1 on 2018-01-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0012_remove_developer_studioname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bought',
            field=models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameshop.Developer'), to='gameshop.Profile'),
        ),
    ]
