# Generated by Django 2.0.1 on 2018-01-24 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameshop', '0012_auto_20180124_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_score', models.TextField(default='NOSAVE')),
                ('save_items', models.TextField(default='NOSAVE')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameshop.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
