# Generated by Django 2.0.2 on 2018-02-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0013_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.CharField(default='http://webcourse.cs.hut.fi/example_game.html', max_length=300),
        ),
    ]
