# Generated by Django 2.0.1 on 2018-01-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0016_profile_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
