# Generated by Django 2.0.2 on 2018-02-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0014_game_url'),
        ('gameshop', '0017_game_price'),
    ]

    operations = [
    ]
