# Generated by Django 2.0.1 on 2018-02-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0018_merge_20180210_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField(default='NULL')),
                ('pid', models.TextField(default='NULL')),
            ],
        ),
    ]
